apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: iacd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: project-backend
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          env:
            - name: MONGO_URL
              value: "mongodb://mongodb-service:27017/course-goals"  # Use the correct service URL
