apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: iacd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: project-frontend
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          volumeMounts:
            - mountPath: /logs  # Monta o volume no diretório /logs
              name: nodejs-logs-volume
      volumes:
        - name: nodejs-logs-volume
          persistentVolumeClaim:
            claimName: nodejs-logs-pvc  # O PVC que criamos
