FROM node:14 AS build

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

EXPOSE 3000

CMD ["sh", "-c", "npm start >> /logs/app.log 2>&1"]

#docker build -t frontend .
#docker run -p 3000:3000 frontend