version: "3.8"

services:

  mongo_container2:
    image: mongo
    volumes:
      - mongo_volume:/data/db
    networks:
      - net
    

  back_container2:
    image: lpseco11/iacd_backend:network
    ports:
      - 80:80
    depends_on:
      - mongo_container2
    networks:
      - net
    volumes:
      - backend_volume:/logs
    stdin_open: true
    tty: true

  front_container2:
    image: lpseco11/iacd_frontend
    ports:
      - 3000:3000
    depends_on:
      - back_container2


volumes:
  mongo_volume:
  backend_volume:

networks:
  net:



