
services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_volume:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 80:80

    depends_on:
      - mongodb
    stdin_open: true
    tty: true

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000


volumes:
  mongo_volume:



