version: "3.8"

services:

  mongo_container:
    image: mongo
    volumes:
      - mongo_volume:/data/db
    ports:
      - 27017:27017

  backend_container:
    image: backend
    ports:
      - 80:80
    depends_on:
      - mongo_container
    

  frontend_container:
    image: frontend
    ports:
      - 4000:3000
    depends_on:
      - backend_container


volumes:
  mongo_volume:
  backend_volume:

# docker-compose up --build

