apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nodejs-logs-pvc
  namespace: iacd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
