apiVersion: v1
kind: PersistentVolume
metadata:
  name: nodejs-logs-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/nodejs-logs  # Caminho no nรณ Minikube para logs
    type: DirectoryOrCreate
